---
version: '3'
services:
  # The environment variable "TAG" is used throughout this file to
  # specify the version of the images to run. The default is set in the
  # '.env' file in this folder. It can be overridden with any normal
  # technique for setting environment variables, for example:
  #
  #   TAG=6.0.0-beta1 docker-compose up
  #
  # REF: https://docs.docker.com/compose/compose-file/#variable-substitution
  #
  # Also be sure to set the ELASTIC_VERSION variable. For released versions,
  # ${TAG} and ${ELASTIC_VERSION} will be identical, but for pre-release
  # versions, ${TAG} might contain an extra build identifier, like
  # "6.0.0-beta1-3eab5b40", so a full invocation might look like:
  #
  #   ELASTIC_VERSION=6.0.0-beta1 TAG=6.0.0-beta1-3eab5b40 docker-compose up
  #
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${TAG}
    container_name: sfn-elasticsearch
    restart: always
    volumes:
      - ./log/elasticsearch/:/var/log/elasticsearch/
      - ./elasticsearch/data/:/usr/share/elasticsearch/data
      - ./elasticsearch/backups/:/usr/share/elasticsearch/backups
      - ./elasticsearch/config/elasticsearch.yml:/etc/elasticsearch/config/elasticsearch.yml
    environment: 
      - http.host=0.0.0.0
      - transport.host=127.0.0.1
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=-Xms4g -Xmx4g
    ports: ['127.0.0.1:9200:9200']
    networks: ['sfn-stack']

  kibana:
    image: docker.elastic.co/kibana/kibana:${TAG}
    container_name: sfn-kibana
    restart: always
    ports: ['127.0.0.1:5601:5601']
    networks: ['sfn-stack']
    depends_on: ['elasticsearch']

  logstash:
    image: docker.elastic.co/logstash/logstash:${TAG}
    container_name: sfn-logstash
    restart: always
    # Provide a simple pipeline configuration for Logstash with a bind-mounted file.
    volumes:
      - ./logstash/pan-sfn.conf:/usr/share/logstash/pipeline/pan-sfn.conf
      - ./log/logstash/:/var/log/logstash
    ports: ['127.0.0.1:5514:5514']
    networks: ['sfn-stack']
    depends_on: ['elasticsearch']

  
networks: {sfn-stack: {}}
